version: '1'
services:
  dev:
    command: "python app.py"
    image: ayenyeintthu95/ml_a2_ayenyeinthu-web:latest
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 5001
      - traefik.http.services.web-st124957.loadbalancer.server.port=5001
      # This config you domain name. By default, your subdomain is web-st124957
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.web-st124957.rule=Host(`st124957.ml.brain.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.web-st124957.tls=true
      - traefik.http.routers.web-st124957.tls.certresolver=production
      - traefik.http.routers.web-st124957.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default

# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true
