version: '3.8'

services:
  web:
    image: rredrose13/ml_a3_ayenyeinthu-web:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    environment:
      - HOST=0.0.0.0
      - PORT=5000
    working_dir: /app
    command: python app.py
