version: '3.8'

services:
  web:
    image: ayenyeintthu95/ml_a2_ayenyeinthu-web:latest
    build:
      context: flask.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    environment:
      - HOST=0.0.0.0
      - PORT=5001
    working_dir: /app
    command: python app.py
